version: '2'
services:
  investapplication3-app:
    image: aleks23202/investapplication:0.4
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://investapplication3-postgresql:5432/investApplication3
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8484:8484
  investapplication3-postgresql:
    extends:
      file: postgresql.yml
      service: investapplication3-postgresql
