export const enum OrderStatus {
  CREATED = 'CREATED',

  SIGN_ONLINE = 'SIGN_ONLINE',

  PAYMENT_CREATED = 'PAYMENT_CREATED',

  CREATED_PACKAGE = 'CREATED_PACKAGE',

  SIGN_PERSON = 'SIGN_PERSON',

  EDIT_BUDGET = 'EDIT_BUDGET',

  PAYMENT_CREATED_DECISION = 'PAYMENT_CREATED_DECISION',

  PAY_DIVIDENTS = 'PAY_DIVIDENTS',
}
