/**
 * investApplication3 API
 * investApplication3 API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FileInfo {
  contentType?: string;
  dataLoad?: string;
  fileName?: string;
  hash?: string;
  id?: number;
  size?: number;
  storageId?: string;
  storageType?: FileInfo.StorageTypeEnum;
}
export namespace FileInfo {
  export type StorageTypeEnum = 'FILE' | 'MONGODB' | 'POSTGRES';
  export const StorageTypeEnum = {
    FILE: 'FILE' as StorageTypeEnum,
    MONGODB: 'MONGODB' as StorageTypeEnum,
    POSTGRES: 'POSTGRES' as StorageTypeEnum,
  };
}
