/**
 * investApplication3 API
 * investApplication3 API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Task entity. @author The JHipster team.
 */
export interface MessagesDTO {
  confirmDate?: Date;
  createDate?: Date;
  employeeId?: number;
  id?: number;
  lotId?: number;
  message?: string;
  notificationType?: MessagesDTO.NotificationTypeEnum;
}
export namespace MessagesDTO {
  export type NotificationTypeEnum = 'EMAIL' | 'TELEGRAM';
  export const NotificationTypeEnum = {
    EMAIL: 'EMAIL' as NotificationTypeEnum,
    TELEGRAM: 'TELEGRAM' as NotificationTypeEnum,
  };
}
