/**
 * investApplication3 API
 * investApplication3 API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface OrdersDTO {
  employeeId?: number;
  endDate?: Date;
  id?: number;
  lotId?: number;
  orderStatus?: OrdersDTO.OrderStatusEnum;
  paymentType?: OrdersDTO.PaymentTypeEnum;
  price?: number;
  startDate?: Date;
}
export namespace OrdersDTO {
  export type OrderStatusEnum =
    | 'CREATED'
    | 'SIGN_ONLINE'
    | 'PAYMENT_CREATED'
    | 'CREATED_PACKAGE'
    | 'SIGN_PERSON'
    | 'EDIT_BUDGET'
    | 'PAYMENT_CREATED_DECISION'
    | 'PAY_DIVIDENTS';
  export const OrderStatusEnum = {
    CREATED: 'CREATED' as OrderStatusEnum,
    SIGNONLINE: 'SIGN_ONLINE' as OrderStatusEnum,
    PAYMENTCREATED: 'PAYMENT_CREATED' as OrderStatusEnum,
    CREATEDPACKAGE: 'CREATED_PACKAGE' as OrderStatusEnum,
    SIGNPERSON: 'SIGN_PERSON' as OrderStatusEnum,
    EDITBUDGET: 'EDIT_BUDGET' as OrderStatusEnum,
    PAYMENTCREATEDDECISION: 'PAYMENT_CREATED_DECISION' as OrderStatusEnum,
    PAYDIVIDENTS: 'PAY_DIVIDENTS' as OrderStatusEnum,
  };
  export type PaymentTypeEnum = 'CACHE' | 'CARD';
  export const PaymentTypeEnum = {
    CACHE: 'CACHE' as PaymentTypeEnum,
    CARD: 'CARD' as PaymentTypeEnum,
  };
}
